dependencies:
  - python=3.7.6
  - pip
  - ipykernel

  - conda-forge::pyyaml=5.3
  - conda-forge::pre_commit=1.16.1
  - pydocstyle=3.0
  - conda-forge::black=19.3
  - conda-forge::darglint=0.6.1
  - flake8=3.7
  - conda-forge::flake8-docstrings=1.3.0
  - isort=4.3.19
  - mypy=0.750

  - pip:
    - pipenv
